/**
 * PMS
 * test rest api for pms
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { WorkPlace } from '../model/workPlace';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FacilitiesManagementService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * returns array of workplace
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facilitiesManagementWorkplacesGet(observe?: 'body', reportProgress?: boolean): Observable<Array<WorkPlace>>;
    public facilitiesManagementWorkplacesGet(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<WorkPlace>>>;
    public facilitiesManagementWorkplacesGet(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<WorkPlace>>>;
    public facilitiesManagementWorkplacesGet(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<WorkPlace>>('get',`${this.basePath}/facilities-management/workplaces`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * create a new workplace
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facilitiesManagementWorkplacesPost(observe?: 'body', reportProgress?: boolean): Observable<WorkPlace>;
    public facilitiesManagementWorkplacesPost(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<WorkPlace>>;
    public facilitiesManagementWorkplacesPost(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<WorkPlace>>;
    public facilitiesManagementWorkplacesPost(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<WorkPlace>('post',`${this.basePath}/facilities-management/workplaces`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * delete workplace by Id
     * 
     * @param workplaceId Id of workplace that needs to be delete
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facilitiesManagementWorkplacesWorkplaceIdDelete(workplaceId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public facilitiesManagementWorkplacesWorkplaceIdDelete(workplaceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public facilitiesManagementWorkplacesWorkplaceIdDelete(workplaceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public facilitiesManagementWorkplacesWorkplaceIdDelete(workplaceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workplaceId === null || workplaceId === undefined) {
            throw new Error('Required parameter workplaceId was null or undefined when calling facilitiesManagementWorkplacesWorkplaceIdDelete.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/facilities-management/workplaces/${encodeURIComponent(String(workplaceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * return workplace by Id
     * 
     * @param workplaceId Id of workplace that needs to be return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facilitiesManagementWorkplacesWorkplaceIdGet(workplaceId: number, observe?: 'body', reportProgress?: boolean): Observable<WorkPlace>;
    public facilitiesManagementWorkplacesWorkplaceIdGet(workplaceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<WorkPlace>>;
    public facilitiesManagementWorkplacesWorkplaceIdGet(workplaceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<WorkPlace>>;
    public facilitiesManagementWorkplacesWorkplaceIdGet(workplaceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workplaceId === null || workplaceId === undefined) {
            throw new Error('Required parameter workplaceId was null or undefined when calling facilitiesManagementWorkplacesWorkplaceIdGet.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<WorkPlace>('get',`${this.basePath}/facilities-management/workplaces/${encodeURIComponent(String(workplaceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * update workplace by Id
     * 
     * @param workplaceId Id of workplace that needs to be update
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public facilitiesManagementWorkplacesWorkplaceIdPut(workplaceId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public facilitiesManagementWorkplacesWorkplaceIdPut(workplaceId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public facilitiesManagementWorkplacesWorkplaceIdPut(workplaceId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public facilitiesManagementWorkplacesWorkplaceIdPut(workplaceId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (workplaceId === null || workplaceId === undefined) {
            throw new Error('Required parameter workplaceId was null or undefined when calling facilitiesManagementWorkplacesWorkplaceIdPut.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('put',`${this.basePath}/facilities-management/workplaces/${encodeURIComponent(String(workplaceId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
