/**
 * PMS
 * REST API for PMS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface FacilitiesManagementHistoryDTO { 
    id?: number;
    type?: string;
    date?: Date;
    user?: any;
    newInfo?: any;
    oldInfo?: any;
}