/**
 * PMS
 * test rest api for pms
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from './address';

export interface Location { 
    id?: number;
    location?: Address;
    comment?: string;
}