/**
 * PMS
 * REST API for PMS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocationDTO } from './locationDTO';
import { WorkAreaDTO } from './workAreaDTO';

export interface WorkPlaceDTO { 
    id?: number;
    name?: string;
    workArea?: WorkAreaDTO;
    location?: LocationDTO;
    floor?: number;
    comment?: string;
}