/**
 * PMS
 * test rest api for pms
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from './location';

export interface WorkPlace { 
    id?: number;
    location?: Location;
    department?: string;
    floor?: number;
    room?: number;
    place?: number;
    comment?: string;
}