swagger: '2.0'
info:
  description: test rest api for pms
  version: 1.0.0
  title: PMS
paths:
  /facilities-management/workplaces:
    get:
      tags:
        - facilities-management
      summary: returns array of workplace
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/WorkPlace'
    post:
      tags:
        - facilities-management
      summary: create a new workplace
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/WorkPlace'
  '/facilities-management/workplaces/{workplaceId}':
    get:
      tags:
        - facilities-management
      summary: return workplace by Id
      parameters:
        - name: workplaceId
          in: path
          description: Id of workplace that needs to be return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/WorkPlace'
        '405':
          description: invalid input
    put:
      tags:
        - facilities-management
      summary: update workplace by Id
      parameters:
        - name: workplaceId
          in: path
          description: Id of workplace that needs to be update
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
    delete:
      tags:
        - facilities-management
      summary: delete workplace by Id
      parameters:
        - name: workplaceId
          in: path
          description: Id of workplace that needs to be delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
        '405':
          description: invalid input
definitions:
  Address:
    type: object
    properties:
      id:
        type: integer
        format: int64
      city:
        type: string
      street:
        type: string
      buildingNumber:
        type: integer
        format: int64
      floors:
        type: integer
        format: int32
  Location:
    type: object
    properties:
      id:
        type: integer
        format: int64
      location:
        $ref: '#/definitions/Address'
      comment:
        type: string
  WorkPlace:
    type: object
    properties:
      id:
        type: integer
        format: int64
      location:
        $ref: '#/definitions/Location'
      department:
        type: string
      floor:
        type: integer
        format: int32
      room:
        type: integer
        format: int32
      place:
        type: integer
        format: int32
      comment:
        type: string
